### ISSUE TITLE
该网站暂时无法进行访问

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/od-api#3]
When I visit http://api.x-lab.info/X-lab2017/open-digger/openrank and http://api.x-lab.info/zhicheng-ning/openrank the web page shows that: 

> 因该网站存在未备案或已备案未接入或涉及发布违禁信息等情况，违反工信部、公安部相关规定而无法访问

**Comment by zhicheng-ning** [comment]
Thanks for your feedback.I just changed a new registgered domain name, you can try again.

**Comment by stevending1st** [comment]
> Thanks for your feedback.I just changed a new registgered domain name, you can try again.

Sorry, I can't visit now. May you tell me the new domain?

**Comment by stevending1st** [comment]
> Thanks for your feedback.I just changed a new registgered domain name, you can try again.

Sorry, I can't visit now. May you tell me the new domain?

**Comment by zhicheng-ning** [comment]
> Sorry, I can't visit now. May you tell me the new domain?
> 

It's http://api.x-lab.info/X-lab2017/open-digger/openrank, actually it will redirect to http://api.nzcer.cn:8081/X-lab2017/open-digger/openrank

**Comment by stevending1st** [comment]
> It's http://api.x-lab.info/X-lab2017/open-digger/openrank, actually it will redirect to http://api.nzcer.cn:8081/X-lab2017/open-digger/openrank

Thank you for your job. But I visit http://api.x-lab.info/X-lab2017/open-digger/openrank, it will redirct to http://api.openrank.cn:8081/X-lab2017/open-digger/openrank.

**Comment by zhicheng-ning** [comment]
> Thank you for your job. But I visit http://api.x-lab.info/X-lab2017/open-digger/openrank, it will redirct to http://api.openrank.cn:8081/X-lab2017/open-digger/openrank.

You can open a new traceless tab and revisit it.

**Comment by stevending1st** [comment]
> You can open a new traceless tab and revisit it.

Thank you for your help, it's ok!
