### ISSUE TITLE
[ci/cd] support issue comment label

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/od-api#35]
You can reference :
- https://github.com/X-lab2017/open-digger/blob/master/.github/workflows/reply-label-issue-comment.yml
- https://github.com/X-lab2017/open-digger/blob/master/.github/workflows/reply-label-issue-open.yml

**Comment by zhicheng-ning** [comment]
Hi  @andyhuang18，are you interested in completing it ? Just refer to the implementiation of OpenDigger.

**Comment by andyhuang18** [comment]
OK！I will work on it.
