### ISSUE TITLE
[feature] Add an API to query which repos are included in a login

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/od-api#39]

**Comment by zhicheng-ning** [comment]
Hi @stevending1st , I'm not sure if l understand what your mean. Do you mean output all public repositories of that user by inputing the user name?

**Comment by stevending1st** [comment]
> Hi @stevending1st , I'm not sure if l understand what your mean. Do you mean output all public repositories of that user by inputing the user name?

I'm sorry, this may not be what I thought.
As we know, OD-API can't query metrics for all repos.
I would like to have an API that gets all the repos that can query metrics, for a login.

**Comment by zhicheng-ning** [comment]
> As we know, OD-API can't query metrics for all repos.

You can see https://github.com/X-lab2017/od-api/issues/15, we now support [many metrics](https://github.com/X-lab2017/od-api#api-documentation) for all repo and user that supported by open-digger actually, we will support more metric in the future.

**Comment by zhicheng-ning** [comment]
> I would like to have an API that gets all the repos that can query metrics, for a login.

If you want to know which repositories can query metrics, I think you should create a issue in [open-digger](https://github.com/X-lab2017/open-digger) which is the upstream project.

**Comment by stevending1st** [comment]
> If you want to know which repositories can query metrics, I think you should create a issue in [open-digger](https://github.com/X-lab2017/open-digger) which is the upstream project.

OK, thank you! ❤️
